### PR TITLE
Implement floating-point to integer conversions and tests

### LINKED ISSUE #85: Implement floating-point to integer conversions
The following opcodes for converting floating-point numbers to integer values should be implemented:

- `i32.trunc_s/f32`
- `i32.trunc_u/f32`
- `i32.trunc_s/f64`
- `i32.trunc_u/f64`
- `i64.trunc_s/f32`
- `i64.trunc_u/f32`
- `i64.trunc_s/f64`
- `i64.trunc_u/f64`

### PR DESCRIPTION
**Pull request by Leonardo2718**
This changeset implements the following opcodes and adds JIT tests for them:

- I32TruncSF32
- I32TruncUF32
- I32TruncSF64
- I32TruncUF64
- I64TruncSF32
- I64TruncSF64

Closes #85

### CODE REVIEW

**Comment by Leonardo2718** [comment]
I am making this WIP for now because there seems to be a problem with how the x86 code generator handles `f2iu` opcodes. I have also disabled (commented out) some of the new tests for the same reason.

I will be spending some time tracking down a solution for this. This PR must not be merged until the problem is resolved.

**Review by aviansie-ben — COMMENTED** [review]
LGTM so far

**Comment by Leonardo2718** [comment]
@aviansie-ben, I've implemented I32TrunUF32 and I32TrunUF64 by truncating to an int64_t first and then converting to uint32_t.

**Review by aviansie-ben — CHANGES_REQUESTED** [review]
Code looks good to me. However, the opcode names in your commit message are misspelled (they should all be `Trunc`, not `Trun`).

**Comment by Leonardo2718** [comment]
@aviansie-ben 

*sigh...*

That's a typo the compiler can't catch. Fixed.

**Review by aviansie-ben — CHANGES_REQUESTED** [review]
Your commit message is mentioning the i64 unsigned truncation opcodes, but you haven't actually implemented those.

**Comment by Leonardo2718** [comment]
Fixed.

**Review by aviansie-ben — APPROVED** [review]

**Pull request merged**
